authors:
  justingoheen:
    name: Justin Goheen # Author name
    description: AI Engineer and Advocate # Author description
    avatar: https://avatars.githubusercontent.com/u/26209687 # Author avatar
